# Generated by Django 4.2.1 on 2023-05-26 04:13

from django.db import migrations, models
import rules.contrib.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'preview_image',
                    models.ImageField(
                        blank=True,
                        upload_to='media',
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Заголовок'),
                ),
                ('text', models.TextField(verbose_name='Полное описание меры')),
                (
                    'amount',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Сумма субсидий',
                    ),
                ),
                (
                    'site',
                    models.URLField(
                        blank=True,
                        verbose_name='Ссылка на сторонний ресурс с подробной информацией',
                    ),
                ),
                (
                    'is_actual',
                    models.BooleanField(
                        default=False,
                        verbose_name='Является ли меря поддержки актуальной',
                    ),
                ),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text='A comma-separated list of tags.',
                        through='taggit.TaggedItem',
                        to='taggit.Tag',
                        verbose_name='Tags',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Мера поддержки бизнеса',
                'verbose_name_plural': 'Меры поддержки бизнеса',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
