# Generated by Django 4.2.1 on 2023-05-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_support'),
    ]

    operations = [
        migrations.DeleteModel(name='Support',),
    ]
