# Generated by Django 4.2.1 on 2023-05-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='amount',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Сумма займа'
            ),
        ),
        migrations.AddField(
            model_name='offer',
            name='interest_rate',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Процентная ставка'
            ),
        ),
        migrations.AddField(
            model_name='offer',
            name='loan_term',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Срок займа'
            ),
        ),
    ]
