# Generated by Django 4.2.1 on 2023-05-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hincal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='year',
            field=models.PositiveIntegerField(
                default=2023, verbose_name='Год, к которому относятся данные'
            ),
        ),
    ]
