# Generated by Django 4.2.1 on 2023-05-25 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.apps.hincal.services.archive


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hincal', '0003_alter_archive_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business', name='sector_valid',
        ),
        migrations.RemoveConstraint(
            model_name='business', name='sub_sector_valid',
        ),
        migrations.AddField(
            model_name='archive',
            name='average_salary',
            field=models.JSONField(
                default=server.apps.hincal.services.archive.get_average_salary,
                verbose_name='Средняя заработная плата по секторам',
            ),
        ),
        migrations.AddField(
            model_name='archive',
            name='income_tax_rate_to_the_federal_budget',
            field=models.FloatField(
                default=0.02,
                verbose_name='Налог на прибыль, уплачиваемый в федеральный бюджет',
            ),
        ),
        migrations.AddField(
            model_name='archive',
            name='income_tax_rate_to_the_subject_budget',
            field=models.FloatField(
                default=0.18,
                verbose_name='Налог на прибыль, уплачиваемый в бюджет субъекта',
            ),
        ),
        migrations.AlterField(
            model_name='archive',
            name='lower_tax_margin_error',
            field=models.FloatField(
                default=0.8,
                verbose_name='Нижний уровень погрешности для поиска записей по налогам',
            ),
        ),
        migrations.AlterField(
            model_name='archive',
            name='property_tax_rate',
            field=models.FloatField(
                default=0.019,
                verbose_name='Размер налоговой ставки на имущество',
            ),
        ),
        migrations.AlterField(
            model_name='archive',
            name='upper_tax_margin_error',
            field=models.FloatField(
                default=1.2,
                verbose_name='Верхний уровень погрешности для поиска записей по налогам',
            ),
        ),
        migrations.AlterField(
            model_name='business',
            name='sector',
            field=models.CharField(
                choices=[
                    ('food_industry', 'Пищевая промышленность'),
                    (
                        'radio_electronics_and_instrumentation',
                        'Радиоэлектроника и приборостроение',
                    ),
                    ('aviation_industry', 'Авиационная промышленность'),
                    ('automotive_industry', 'Автомобильная промышленность'),
                    ('general_mechanical_engineering', 'Общее машиностроение'),
                    ('light_industry', 'Легкая промышленность'),
                    (
                        'production_of_petroleum_products',
                        'Производство кокса и нефтепродуктов',
                    ),
                    ('chemical_industry', 'Химическая промышленность'),
                    (
                        'production_of_building_materials',
                        'Химическая промышленность',
                    ),
                    (
                        'production_for_military',
                        'Производство оружия, боеприпасов, спецхимии, военных машин',
                    ),
                    (
                        'pharmaceutical_industry',
                        'Фармацевтическая промышленность',
                    ),
                    (
                        'fuel_and_energy_complex',
                        'Топливно-энергетический комплекс',
                    ),
                    ('medical_industry', 'Медицинская промышленность'),
                    ('cable_industry', 'Кабельная промышленность'),
                    ('woodworking', 'Деревообрабатывающая'),
                    (
                        'metallurgy_and_metalworking',
                        'Металлургия и металлообработка',
                    ),
                    ('printing_activity', 'Полиграфическая деятельность'),
                    (
                        'production_of_other_consumer_goods',
                        'Производство прочих товаров народного потребления',
                    ),
                    ('beverage_production', 'Производство напитков'),
                    ('scientific_activity', 'Научная деятельность'),
                    (
                        'machine_tool_industry',
                        'Станкоинструментальная промышленность',
                    ),
                    ('shipbuilding', 'Судостроение'),
                    (
                        'production_of_railway_transport',
                        'Производство ж/д транспорта',
                    ),
                    (
                        'manufacture_of_consumer_electronics',
                        'Производство бытовой электроники и электрических приборов',
                    ),
                    ('additive_technologies', 'Аддитивные технологии'),
                    ('other', 'Иные сектора'),
                ],
                max_length=255,
                verbose_name='Отрасль хозяйственной деятельности',
            ),
        ),
        migrations.AlterField(
            model_name='business',
            name='sub_sector',
            field=models.CharField(
                choices=[
                    ('dairy_industry', 'Молочная отрасль'),
                    ('instrumentation', 'Приборостроение'),
                    ('meat_industry', 'Мясная отрасль'),
                    ('confectionery_industry', 'Кондитерская отрасль'),
                    (
                        'manufacture_of_other_general',
                        'Производство прочих машин и оборудования общего назначения',
                    ),
                    ('bakery_industry', 'Хлебопекарная отрасль'),
                    (
                        'production_of_railway_transport',
                        'Производство ж/д транспорта',
                    ),
                    ('fishing_industry', 'Рыбная отрасль'),
                    (
                        'production_of_general_purpose_equipment',
                        'Производство машин и оборудования общего назначения',
                    ),
                    (
                        'production_of_canned_fruits_and_vegetables',
                        'Производство плодоовощных консервов',
                    ),
                    ('electrical_engineering', 'Электротехника'),
                    (
                        'production_of_other_special_purpose_machines',
                        'Производство прочих машин специального назначения',
                    ),
                    (
                        'machine_tool_industry',
                        'Станкоинструментальная промышленность',
                    ),
                    ('microelectronics', 'Микроэлектроника'),
                    (
                        'milling_and_cereal_industry',
                        'Мукомольно-крупяная отрасль',
                    ),
                    ('other', 'Иные подсектора'),
                    ('beverage_production', 'Производство напитков'),
                    ('animal_feed', 'Корма для животных'),
                    (
                        'electrical_engineering_and_shipbuilding',
                        'Электротехника/Судостроение',
                    ),
                    ('sugar_industry', 'Сахарная отрасль'),
                    (
                        'production_of_equipment_for_agriculture_and_forestry',
                        'Производство машин и оборудования для сельского и лесного хозяйства',
                    ),
                    ('fat_and_oil_industry', 'Масложировая отрасль'),
                    ('metalworking', 'Металлообработка'),
                ],
                max_length=255,
                verbose_name='Подотрасль хозяйственной деятельности',
            ),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reports',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'sector__in',
                        [
                            'food_industry',
                            'radio_electronics_and_instrumentation',
                            'aviation_industry',
                            'automotive_industry',
                            'general_mechanical_engineering',
                            'light_industry',
                            'production_of_petroleum_products',
                            'chemical_industry',
                            'production_of_building_materials',
                            'production_for_military',
                            'pharmaceutical_industry',
                            'fuel_and_energy_complex',
                            'medical_industry',
                            'cable_industry',
                            'woodworking',
                            'metallurgy_and_metalworking',
                            'printing_activity',
                            'production_of_other_consumer_goods',
                            'beverage_production',
                            'scientific_activity',
                            'machine_tool_industry',
                            'shipbuilding',
                            'production_of_railway_transport',
                            'manufacture_of_consumer_electronics',
                            'additive_technologies',
                            'other',
                        ],
                    )
                ),
                name='sector_valid',
            ),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'sub_sector__in',
                        [
                            'dairy_industry',
                            'instrumentation',
                            'meat_industry',
                            'confectionery_industry',
                            'manufacture_of_other_general',
                            'bakery_industry',
                            'production_of_railway_transport',
                            'fishing_industry',
                            'production_of_general_purpose_equipment',
                            'production_of_canned_fruits_and_vegetables',
                            'electrical_engineering',
                            'production_of_other_special_purpose_machines',
                            'machine_tool_industry',
                            'microelectronics',
                            'milling_and_cereal_industry',
                            'other',
                            'beverage_production',
                            'animal_feed',
                            'electrical_engineering_and_shipbuilding',
                            'sugar_industry',
                            'production_of_equipment_for_agriculture_and_forestry',
                            'fat_and_oil_industry',
                            'metalworking',
                        ],
                    )
                ),
                name='sub_sector_valid',
            ),
        ),
    ]
