# Generated by Django 4.2.1 on 2023-05-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hincal', '0005_alter_business_inn_alter_business_sub_sector'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business', name='sub_sector_valid',
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'sub_sector__in',
                        [
                            'dairy_industry',
                            'instrumentation',
                            'meat_industry',
                            'confectionery_industry',
                            'manufacture_of_other_general',
                            'bakery_industry',
                            'production_of_railway_transport',
                            'fishing_industry',
                            'production_of_general_purpose_equipment',
                            'production_of_canned_fruits_and_vegetables',
                            'electrical_engineering',
                            'production_of_other_special_purpose_machines',
                            'machine_tool_industry',
                            'microelectronics',
                            'milling_and_cereal_industry',
                            'other',
                            'beverage_production',
                            'animal_feed',
                            'electrical_engineering_and_shipbuilding',
                            'sugar_industry',
                            'production_of_equipment_for_agriculture_and_forestry',
                            'fat_and_oil_industry',
                            'metalworking',
                            '',
                        ],
                    )
                ),
                name='sub_sector_valid',
            ),
        ),
    ]
