# Generated by Django 4.2.1 on 2023-05-26 08:15

from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        (
            'hincal',
            '0007_businessindicator_sector_alter_business_sector_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSector',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Создан'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='Изменен'),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='Название'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        verbose_name='Название на английском языке',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Подотрасль',
                'verbose_name_plural': 'Подотрасли',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={
                'ordering': ['-id'],
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
            },
        ),
        migrations.RemoveConstraint(
            model_name='business', name='sector_valid',
        ),
        migrations.RemoveConstraint(
            model_name='business', name='sub_sector_valid',
        ),
        migrations.AlterField(
            model_name='business',
            name='sector',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='businesses',
                to='hincal.sector',
                verbose_name='Отрасль хозяйственной деятельности',
            ),
        ),
        migrations.AlterField(
            model_name='business',
            name='sub_sector',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='business',
                to='hincal.subsector',
                verbose_name='Подотрасль хозяйственной деятельности',
            ),
        ),
    ]
