# Generated by Django 4.2.1 on 2023-05-26 12:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('hincal', '0008_subsector_alter_sector_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(model_name='archive', name='average_salary',),
        migrations.RemoveField(
            model_name='archive', name='possible_income_from_patent',
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags',
            ),
        ),
        migrations.AddField(
            model_name='sector',
            name='avg_salary_of_staff',
            field=models.FloatField(
                default=100,
                verbose_name='Средняя заработная плата сотрудника, тыс. руб.',
            ),
        ),
        migrations.AddField(
            model_name='sector',
            name='possible_income_from_patent',
            field=models.PositiveIntegerField(
                default=10000,
                verbose_name='Возможный доход по патентной системе налогообложения, тыс. руб.',
            ),
        ),
        migrations.AddField(
            model_name='sector',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags',
            ),
        ),
    ]
