# Generated by Django 4.2.1 on 2023-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hincal', '0010_territoriallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='avg_land_cadastral_value',
            field=models.FloatField(
                default=17.23389,
                verbose_name='Средняя кадастровая стоимость на землю, тыс. руб.',
            ),
        ),
        migrations.AddField(
            model_name='archive',
            name='avg_property_cadastral_value',
            field=models.FloatField(
                default=17.23389,
                verbose_name='Средняя кадастровая стоимость на имуществу, тыс. руб.',
            ),
        ),
    ]
