# Generated by Django 4.2.1 on 2023-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hincal', '0011_archive_avg_land_cadastral_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='territoriallocation',
            name='extra_data',
            field=models.JSONField(
                blank=True, null=True, verbose_name='Дополнительные параметры'
            ),
        ),
    ]
