# Generated by Django 4.2.1 on 2023-05-26 21:56

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('hincal', '0012_territoriallocation_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='disability_contributions_rate',
            field=models.FloatField(
                default=0.029,
                verbose_name='Размер ставки для по нетрудоспособности',
            ),
        ),
        migrations.AddField(
            model_name='archive',
            name='osn_tax_rate',
            field=models.FloatField(
                default=0.2,
                verbose_name='Размер налоговой ставки по общей системе налогооблажения',
            ),
        ),
        migrations.AddField(
            model_name='archive',
            name='ysn_tax_rate',
            field=models.FloatField(
                default=0.06,
                verbose_name='Размер налоговой ставки по упрощенной системе налогооблажения',
            ),
        ),
        migrations.AddField(
            model_name='business',
            name='type_tax_system',
            field=models.CharField(
                choices=[
                    ('osn', 'Общая'),
                    ('ysn', 'Упрощенная'),
                    ('patent', 'Патентная'),
                ],
                default='osn',
                max_length=255,
                verbose_name='Тип системы налогооблажения',
            ),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags',
            ),
        ),
        migrations.AddField(
            model_name='sector',
            name='possible_income',
            field=models.PositiveIntegerField(
                default=10000, verbose_name='Возможный доход, тыс. руб.'
            ),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('type_tax_system__in', ['osn', 'ysn', 'patent'])
                ),
                name='type_tax_system_valid',
            ),
        ),
    ]
