# Generated by Django 4.2.1 on 2023-05-27 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hincal', '0014_archive_avg_land_lease_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sector',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reports',
                to='hincal.sector',
                verbose_name='Отрасль хозяйственной деятельности',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='total_investment_amount_bi',
            field=models.FloatField(
                null=True, verbose_name='Общая сумма инвестирований из БД'
            ),
        ),
        migrations.AddField(
            model_name='report',
            name='total_investment_amount_math',
            field=models.FloatField(
                null=True,
                verbose_name='Общая сумма инвестирований, рассчитанная математически',
            ),
        ),
        migrations.DeleteModel(name='Statistic',),
    ]
