# Generated by Django 4.2.1 on 2023-05-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'hincal',
            '0015_report_sector_report_total_investment_amount_bi_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='avg_capital_construction_costs',
            field=models.FloatField(
                default=100,
                verbose_name='Затраты на капитальное строительство, тыс. руб.',
            ),
        ),
        migrations.AlterField(
            model_name='archive',
            name='lower_tax_margin_error',
            field=models.FloatField(
                default=0.85,
                verbose_name='Нижний уровень погрешности для поиска записей по налогам',
            ),
        ),
        migrations.AlterField(
            model_name='archive',
            name='upper_tax_margin_error',
            field=models.FloatField(
                default=1.15,
                verbose_name='Верхний уровень погрешности для поиска записей по налогам',
            ),
        ),
    ]
